// Info-card database. All numbers are approximate public figures (SpaceX statements, NASASpaceflight, Wikipedia; checked Sep 2026).
// The 3D model depicts the Block 2 (V2) vehicle, which last flew on Flight 11 (Oct 13 2025); Block 3 / V3 has flown since May 22 2026.
export const INFO = {
  // ---------- stage summaries
  stack: { t: 'Starship (full stack)', tag: 'Ship + Super Heavy',
    d: 'Fully reusable two-stage super heavy-lift launch vehicle. This model shows the Block 2 (V2) stack, which flew in 2025 and was retired after Flight 11 (Oct 13 2025): the Ship sat on the Super Heavy booster, joined by a separate vented hot-staging ring. Block 3 (V3, flying since May 2026) integrates that vented section into the booster.',
    s: [['Height', '~123 m (Block 2) · ~124.4 m (Block 3)'], ['Diameter', '9 m'], ['Engines', '33 (booster) + 6 (ship) Raptors'], ['Propellant', 'Liquid oxygen (LOX) + liquid methane (CH₄)'], ['Total propellant', '~4,750–4,900 t (Block 2; estimates vary)'], ['Block 3 (V3)', 'First flew May 22 2026 (Flight 12)']] },
  booster: { t: 'Super Heavy booster', tag: 'First stage',
    d: 'Stainless-steel first stage. Burns for ~2.5 minutes, then flips, boosts back and returns to be caught by the launch tower\'s "chopsticks" (or splashes down on test flights). Model shows the Block 2-era booster (4 grid fins, separate hot-staging ring).',
    s: [['Height', '~71 m incl. hot-staging ring (Block 1/2) · ~72.3 m (Block 3)'], ['Diameter', '9 m'], ['Propellant', '~3,400 t (Block 1/2: ≈2,700 t LOX + ≈700 t CH₄) · ~3,650 t (Block 3, reported)'], ['Engines', '33 Raptor (13 gimbaled inner, 20 fixed outer)'], ['Liftoff thrust', '~74 MN w/ Raptor 2 · ~81 MN Block 3 (33 × ~250 tf Raptor 3)']] },
  ship: { t: 'Starship (Ship)', tag: 'Upper stage / spacecraft',
    d: 'The upper stage and spacecraft. Reaches space on 3 sea-level + 3 vacuum Raptors, re-enters belly-first on its heat shield, steering with 4 flaps, then flips upright for landing. Model shows the Block 2 ship.',
    s: [['Height', '~50.3 m (Block 1) / ~52.1 m (Block 2)'], ['Diameter', '9 m'], ['Propellant', '~1,200 t (Block 1) / ~1,500 t (Block 2) / ~1,600 t (Block 3, reported)'], ['Engines', '3 Raptor sea-level + 3 Raptor Vacuum (RVac)'], ['Payload (planned)', '100+ t reusable on V3 (figures vary by source/version)']] },
  raptor: { t: 'Raptor engine', tag: 'Full-flow staged combustion',
    d: 'Methane/oxygen engine using the full-flow staged combustion cycle: nearly all the oxygen passes through an oxygen-rich preburner and nearly all the methane through a fuel-rich preburner (each gets a small cross-feed of the other propellant), so both propellants enter the main chamber as hot gas. Tap components to learn more.',
    s: [['Thrust (Raptor 2, SL)', '~230 tf (~2.26 MN)'], ['Thrust (Raptor 3, SL)', '~250 tf nominal (SpaceX, May 2026); 280 tf reached in 2024 testing'], ['RVac thrust', '~258 tf (R2) / ~275 tf (R3, SpaceX 2026)'], ['Chamber pressure', '~300 bar (R2) · ~330 bar R3 operational (reported), ~350 bar in R3 tests'], ['Isp', '~327 s SL · ~350 s vac (SL engine) · ~380 s RVac'], ['Mixture ratio', '~3.6 : 1 (O₂ : CH₄ by mass)'], ['Size', '~1.3 m dia × ~3.1 m tall (SL)']] },

  model: { t: 'Which Starship is this?', tag: 'Model: Block 2 (2025, retired)',
    d: 'The 3D model shows the Block 2 (V2) Ship with the Block 1/2-style Super Heavy: 4 grid fins, a separate vented hot-staging ring and Raptor 2 engines. That configuration last flew on Flight 11 (Oct 13 2025). Block 3 (V3) has flown since Flight 12 (May 22 2026) with Raptor 3 engines, an integrated hot-stage section, 3 larger grid fins that double as catch points, and more propellant.',
    s: [['Model', 'Block 2 (2025, retired)'], ['Last Block 2 flight', 'Flight 11 · Oct 13 2025'], ['Block 3 first flight', 'Flight 12 · May 22 2026'], ['Block 3 booster', '~72.3 m · ~3,650 t propellant (reported) · ~81 MN'], ['Block 3 ship', '~1,600 t propellant (reported)'], ['Raptor 3 (SpaceX)', '~250 tf SL · ~275 tf vac']],
    note: 'Block 3 propellant loads come from media/Wikipedia reporting and some sources differ.' },

  // ---------- booster parts
  b_skirt: { t: 'Booster aft skirt / engine bay', tag: 'Super Heavy · structure',
    d: 'Skirt surrounding the 33 engines. Holds the outer ring of 20 engines and protects plumbing. Raptor 3 removes most engine shielding by integrating plumbing into the engine.',
    s: [['Engines inside', '33'], ['Engine protrusion', '~3 m below the steel skirt']] },
  b_lox: { t: 'Booster LOX tank', tag: 'Super Heavy · lower (aft) tank',
    d: 'Largest tank on the vehicle, holding liquid oxygen at the BOTTOM of the booster. Its aft "thrust dome" carries the thrust puck where the 13 inner engines mount. The methane downcomer runs straight through its center.',
    s: [['Contents', '~2,700 t liquid oxygen, subcooled (Block 1/2; V3 carries more)'], ['Share of propellant', '~78% by mass (3.6:1 ratio)'], ['Wall', '4 mm-class 30X stainless steel rings (approx.)']], note: 'Tank heights in this model are estimated from propellant volumes.' },
  b_ch4: { t: 'Booster methane (CH₄) tank', tag: 'Super Heavy · upper (forward) tank',
    d: 'Upper booster tank holding liquid methane. It sits ABOVE the LOX tank, separated by a shared "common dome". Methane drains into a sump and down the central transfer tube to the engines.',
    s: [['Contents', '~700 t liquid methane (Block 1/2)'], ['Density', '~0.42–0.45 t/m³ vs LOX ~1.14–1.2 t/m³']] },
  b_fwd: { t: 'Booster forward section', tag: 'Super Heavy · structure',
    d: 'Top of the Block 1/2 booster above the methane forward dome. Carried the grid fins, their electric actuators and the catch hardpoints used by the tower chopsticks. On Block 3 the fins moved lower, into pockets in the methane tank, and double as the catch points.',
    s: [['Grid fins', '4 (Block 1/2), 3 larger fins on Block 3']] },
  b_aftdome: { t: 'Booster aft (thrust) dome', tag: 'Super Heavy · tank dome',
    d: 'Bottom dome of the LOX tank. Heavy internal reinforcement and the thrust puck at its center take the load of the 13 inner engines.', s: [] },
  b_commondome: { t: 'Booster common dome', tag: 'Super Heavy · tank dome',
    d: 'Single shared bulkhead separating methane (above) from liquid oxygen (below). Saves the mass and length of a separate inter-tank. Became more elliptical after Flight 2.', s: [] },
  b_fwddome: { t: 'Booster forward dome', tag: 'Super Heavy · tank dome',
    d: 'Top dome of the methane tank. During hot staging the Ship\'s engines fire toward it; on Block 1/2 boosters (as modelled) a shield dome in the separate vented interstage protected it. Block 3 integrates the vented hot-stage section into the booster.', s: [] },
  b_downcomer: { t: 'Methane downcomer (transfer tube)', tag: 'Super Heavy · plumbing',
    d: 'Large pipe carrying liquid methane from the CH₄ tank sump straight down through the middle of the LOX tank to the engine manifolds. Block 3 boosters got a much larger redesigned transfer tube (SpaceX: roughly the size of a Falcon 9 first stage) for faster, simultaneous engine start.',
    s: [['Diameter here', '~1.6 m (illustrative)']], note: 'Diameter/route approximate.' },
  b_header: { t: 'LOX header / landing tank', tag: 'Super Heavy · tank',
    d: 'Small LOX tank near the bottom of the main LOX tank that feeds the inner engines during the landing burn, when the main tank is nearly empty and propellant sloshes. Design has changed repeatedly (extra tanks were added on Booster 15; Block 3 uses a redesigned landing tank — some reports place it against the tank wall, but SpaceX has not detailed it).',
    s: [], note: 'Shape and placement here are schematic.' },
  b_feed: { t: 'Engine feed manifolds', tag: 'Super Heavy · plumbing',
    d: 'Below the thrust puck, methane and oxygen are split to 33 engines: inner engines are fed through the thrust puck, the outer 20 via ring manifolds. Filters were added here from Booster 10 on.',
    s: [], note: 'Routing drawn schematically.' },
  b_puck: { t: 'Thrust puck', tag: 'Super Heavy · structure',
    d: 'Massive machined structure at the center of the aft dome where the 13 inner (gimbaled) engines mount and propellant passes through into the engines.', s: [] },
  b_mountring: { t: 'Outer engine mount ring', tag: 'Super Heavy · structure',
    d: 'The 20 outer engines are fixed (non-gimbaling) and mount to a ring attached to the skirt, not to the puck.', s: [] },
  b_gridfin: { t: 'Grid fins', tag: 'Super Heavy · aerodynamics',
    d: 'Steel lattice fins that steer the booster during boostback and descent. Electrically actuated. Block 3 boosters switch to 3 larger fins.',
    s: [['Count', '4 (Block 1/2) · 3 (Block 3)']] },
  b_chine: { t: 'Aerodynamic chines', tag: 'Super Heavy · aerodynamics',
    d: 'Strakes along the LOX tank that add lift and stability on descent. They also house batteries, COPVs (pressure bottles for engine spin-start) and CO₂ tanks for fire suppression.', s: [] },
  b_pins: { t: 'Catch hardpoints', tag: 'Super Heavy · structure',
    d: 'Reinforced hardpoints between the grid fins (Block 1/2) that rest on the tower chopsticks when the booster is lifted or caught. On Block 3 the catch points are built into the grid fins instead.', s: [], note: 'Position approximate.' },
  hsr: { t: 'Hot-staging ring (vented interstage)', tag: 'Interface Ship ↔ booster',
    d: 'Open-lattice ring between the stages. Starship "hot stages": the Ship lights its engines while still attached, and the exhaust escapes through the vents. A dome shield protected the booster\'s forward dome, and from Booster 11 on the ring was jettisoned after boostback. On Block 3 the vented section is integrated into the booster and no longer jettisoned.',
    s: [['Height', '~1.8–2 m'], ['First used', 'Flight 2 (Nov 2023)']] },
  b_stringers: { t: 'Stringers', tag: 'Structure',
    d: 'Vertical stiffeners welded inside the tank walls. They let the thin steel rings carry huge compressive loads. Roughly 74 per tank on Super Heavy (model shows fewer).', s: [] },
  b_rings: { t: 'Steel rings / weld seams', tag: 'Structure',
    d: 'Both stages are stacks of stainless-steel rings (~9 m diameter, a few mm thick) that are rolled, welded into stacks, then stacked into tanks.', s: [] },

  // ---------- ship parts
  s_skirt: { t: 'Ship aft skirt / engine bay', tag: 'Ship · structure',
    d: 'Unlike the booster, the Ship\'s engines are fully enclosed by the skirt. It carries the aft flaps and part of the heat shield.', s: [] },
  s_lox: { t: 'Ship LOX tank', tag: 'Ship · lower (aft) tank',
    d: 'Liquid oxygen at the bottom of the Ship. The 3 RVacs mount to its reinforced aft dome; the 3 sea-level engines mount to the thrust puck at its center.',
    s: [['Contents', '~1,150 t LOX (Block 2, est.)']], note: 'Split estimated from ~1,500 t total at 3.6:1.' },
  s_ch4: { t: 'Ship methane (CH₄) tank', tag: 'Ship · upper (forward) tank',
    d: 'Liquid methane above the LOX tank, separated by a common dome. Fed down four downcomers: one central (to the 3 sea-level engines) and three smaller ones (to the RVacs).',
    s: [['Contents', '~330 t CH₄ (Block 2, est.)']] },
  s_aftdome: { t: 'Ship aft (thrust) dome', tag: 'Ship · tank dome', d: 'Bottom of the LOX tank. RVacs attach directly to it with internal reinforcements; the thrust puck at the center holds the 3 sea-level Raptors.', s: [] },
  s_commondome: { t: 'Ship common dome', tag: 'Ship · tank dome', d: 'Shared bulkhead between methane (above) and oxygen (below). A sump in its center collects methane for the central downcomer.', s: [] },
  s_fwddome: { t: 'Ship forward dome', tag: 'Ship · tank dome', d: 'Top of the methane tank and floor of the payload bay. Header-tank downcomers pass through cut-outs here.', s: [] },
  s_downcomer: { t: 'Ship methane downcomers', tag: 'Ship · plumbing',
    d: 'Methane travels through the LOX tank in 4 downcomers: a central one (via a large sump) feeding the 3 sea-level engines and 3 smaller ones feeding the 3 RVacs.', s: [], note: 'Sizes/positions schematic.' },
  s_headerlines: { t: 'Header-tank downcomers', tag: 'Ship · plumbing',
    d: 'Two long lines bring landing propellant from the header tanks in the nose all the way down to the engines. In this model they run along the tank wall.', s: [], note: 'Exact routing is not public; drawn schematically.' },
  s_loxheader: { t: 'LOX header tank', tag: 'Ship · landing propellant',
    d: 'Small tank forming the very top of the nosecone. Holds oxygen for the landing flip & burn, isolated from main-tank slosh. Its forward location also helps pull the center of gravity forward for stable belly-flop re-entry.', s: [] },
  s_ch4header: { t: 'CH₄ header tank', tag: 'Ship · landing propellant',
    d: 'Methane landing tank mounted directly below the LOX header in the nose (moved from the common-dome area to the nose starting with Ship 24). COPVs for engine start are mounted around it.', s: [] },
  s_bay: { t: 'Payload bay', tag: 'Ship · cargo',
    d: 'Pressurisable volume between the forward dome and the nose. On test flights it holds a "PEZ dispenser" for Starlink simulators; future versions add a larger cargo door, crew cabins or propellant (tanker).',
    s: [['Volume', '~600 m³ class (varies)']] },
  s_door: { t: 'Payload door (PEZ slot)', tag: 'Ship · cargo',
    d: 'Slot door used on test flights to deploy Starlink (simulator) satellites one at a time from the PEZ-style dispenser.', s: [], note: 'Size and position approximate.' },
  s_nose: { t: 'Nosecone', tag: 'Ship · structure',
    d: 'Ogive nose with heavy internal reinforcement for the forward flaps and tower lifting points. Contains the header tanks at the tip.', s: [] },
  s_fflap: { t: 'Forward flaps (×2)', tag: 'Ship · aerodynamics',
    d: 'Smaller flaps near the nose. Together with the aft flaps they steer the Ship during belly-flop re-entry, like a skydiver\'s arms and legs. Moved leeward and shrunk on Block 2 to reduce heating.', s: [] },
  s_aflap: { t: 'Aft flaps (×2)', tag: 'Ship · aerodynamics',
    d: 'Large flaps mounted at the engine bay/LOX tank. Electrically actuated; control pitch/roll during re-entry and the landing flip.', s: [] },
  s_tiles: { t: 'Heat shield (TPS tiles)', tag: 'Ship · thermal protection',
    d: 'Around 18,000 hexagonal ceramic tiles pinned to the windward side (the "belly"). Hex shapes avoid straight gaps that hot plasma could flow along. The leeward side is bare stainless steel.',
    s: [['Tile count', '~18,000 (public estimates)'], ['Peak heating', '~1,400 °C class on re-entry']] },
  s_stringers: { t: 'Stringers', tag: 'Structure', d: 'Vertical stiffeners inside Ship tank walls. Block 2 added stringers to the methane tank as well.', s: [] },
  s_puck: { t: 'Ship thrust puck', tag: 'Ship · structure', d: 'Center of the aft dome where the three gimbaling sea-level Raptors mount.', s: [] },

  // ---------- engines (vehicle scale)
  e_center: { t: 'Raptor – center engine (booster)', tag: 'Super Heavy · 3 center engines', d: 'One of the 3 central engines. Gimbaled for steering. On Block 1/2 these 3 engines finished the landing burn on their own; the Block 3 profile (first tested on Flight 11) steps down 13 → 5 → 3 engines for extra redundancy.', s: [['Thrust', '~230 tf (R2) · ~250 tf (R3 nominal)'], ['Gimbal', 'Yes (electric actuators since Flight 2)']], raptor: true },
  e_inner: { t: 'Raptor – inner ring (booster)', tag: 'Super Heavy · 10 inner-ring engines', d: 'One of 10 inner-ring engines. Together with the center 3 these 13 engines gimbal. With Raptor 2 (as modelled) only these 13 could relight for boostback and landing; on Block 3 all 33 Raptor 3s can relight.', s: [['Thrust', '~230 tf (R2) · ~250 tf (R3 nominal)'], ['Gimbal', 'Yes']], raptor: true },
  e_outer: { t: 'Raptor – outer ring (booster)', tag: 'Super Heavy · 20 fixed engines', d: 'One of 20 fixed outer engines. With Raptor 2 they were started by ground equipment and could not relight; Raptor 3 outer engines can relight.', s: [['Thrust', '~230 tf (R2) · ~250 tf (R3 nominal)'], ['Gimbal', 'No (fixed)']], raptor: true },
  e_sl: { t: 'Raptor sea-level (Ship)', tag: 'Ship · 3 center engines', d: 'Gimbaled sea-level Raptors used for steering and the landing burn.', s: [['Thrust', '~230 tf (R2) · ~250 tf (R3 nominal)'], ['Nozzle exit', '~1.3 m']], raptor: true },
  e_rvac: { t: 'Raptor Vacuum (RVac)', tag: 'Ship · 3 outer engines', d: 'Vacuum-optimised Raptor with a huge nozzle (expansion ratio ~80+). Fixed (does not gimbal). Most efficient engine on the vehicle.', s: [['Thrust', '~258 tf (R2) · ~275 tf (R3, SpaceX 2026)'], ['Isp', '~380 s'], ['Nozzle exit', '~2.3 m (approx.)']], raptor: true },

  // ---------- Raptor detail components
  r_loxin: { t: 'LOX inlet', tag: 'Raptor · oxidizer feed', d: 'Subcooled liquid oxygen arrives from the tank (~ -200 °C, colder than its boiling point to pack in more mass).', s: [] },
  r_ch4in: { t: 'Methane inlet', tag: 'Raptor · fuel feed', d: 'Subcooled liquid methane arrives from the downcomer / manifold.', s: [] },
  r_otp: { t: 'Oxygen turbopump (OTP)', tag: 'Raptor · oxidizer side', d: 'Pump raises LOX pressure to several hundred bar. It is spun by a turbine driven by hot OXYGEN-RICH gas from the ox preburner — so the turbine must survive hot, high-pressure oxygen (SpaceX developed special SX500 alloy).', s: [['Drive', 'Ox-rich turbine']], note: 'Layout simplified for clarity.' },
  r_ftp: { t: 'Fuel turbopump (FTP)', tag: 'Raptor · fuel side', d: 'Pumps liquid methane. Driven by a turbine running on hot FUEL-RICH gas from the fuel preburner. Separate shafts for each propellant avoid needing inter-propellant seals.', s: [['Drive', 'Fuel-rich turbine']], note: 'Layout simplified for clarity.' },
  r_oxpb: { t: 'Oxygen-rich preburner', tag: 'Raptor · power cycle', d: 'Nearly all of the engine\'s oxygen flows THROUGH this preburner. A small amount of methane burns with part of that oxygen, turning the whole flow into hot, oxygen-rich gas that drives the OTP turbine and then flows on to the main injector, where the rest of the oxygen finally burns. Ignited by a torch igniter.', s: [] },
  r_fuelpb: { t: 'Fuel-rich preburner', tag: 'Raptor · power cycle', d: 'Mirror image of the ox-rich side: nearly all of the methane (after cooling the nozzle) flows THROUGH this preburner, where a small amount of oxygen burns with part of it to make hot, fuel-rich gas. That gas drives the FTP turbine, then goes to the main injector.', s: [] },
  r_hgm: { t: 'Hot-gas manifolds', tag: 'Raptor · power cycle', d: 'Collect turbine exhaust — oxygen-rich gas and fuel-rich gas — and deliver both to the injector. Because both arrive as gas (gas-gas combustion), mixing is fast and the chamber can be compact.', s: [] },
  r_injector: { t: 'Main injector', tag: 'Raptor · combustion', d: 'Face plate with many coaxial elements that mix the two hot gas streams at very high pressure.', s: [] },
  r_mcc: { t: 'Main combustion chamber', tag: 'Raptor · combustion', d: 'Where the two gas streams burn at ~300+ bar and roughly 3,500 °C (independent estimate; SpaceX has not published a figure). Its copper-alloy liner is cooled by methane flowing through channels in the wall (regenerative cooling).', s: [['Pressure', '~300 bar (R2) · ~330 bar R3 operational (reported), ~350 bar in tests']] },
  r_throat: { t: 'Throat', tag: 'Raptor · nozzle', d: 'Narrowest point — flow reaches the speed of sound here and becomes supersonic in the expanding nozzle. Highest heat flux in the engine.', s: [] },
  r_nozzle: { t: 'Regeneratively cooled nozzle', tag: 'Raptor · nozzle', d: 'Bell nozzle expands exhaust to ~3–3.5 km/s. Methane from the fuel pump runs through hundreds of tiny channels in the wall, cooling it and picking up heat before heading to the fuel preburner.', s: [['Expansion ratio', '~34 (SL) · ~80+ (RVac)']] },
  r_regen: { t: 'Coolant manifolds', tag: 'Raptor · cooling', d: 'Ring manifolds that distribute methane into the nozzle cooling channels and collect it at the top of the chamber.', s: [], note: 'Real routing is more complex.' },
  r_gimbal: { t: 'Gimbal / thrust block', tag: 'Raptor · structure', d: 'Transfers thrust into the vehicle. On gimbaled engines electric actuators tilt the whole engine several degrees to steer.', s: [] },
  r_xfeed: { t: 'Preburner cross-feeds', tag: 'Raptor · power cycle', d: 'Each preburner needs a little of the other propellant to burn: a small LOX flow to the fuel-rich preburner and a small methane flow to the ox-rich preburner. The bulk of each propellant still passes through its own preburner.', s: [], note: 'Schematic.' },
  r_rvac: { t: 'RVac nozzle extension', tag: 'Raptor Vacuum', d: 'The vacuum variant uses the same powerhead with a much bigger nozzle (~2.3 m exit) for higher efficiency in space. It would suffer flow separation at sea level.', s: [['Isp', '~380 s']] },
};

// Overrides used when the deep dive shows the V3 approximation (starship.html?v=3, the default).
// Only the booster's visible V3 changes are modelled; everything else keeps Block 2 geometry, and the cards say so.
export const INFO_V3 = {
  stack: { ...INFO.stack,
    d: 'Fully reusable two-stage super heavy-lift launch vehicle. This view approximates Starship V3 (Block 3, flying since Flight 12 on May 22 2026): the booster shows V3’s three larger grid fins and integrated vented hot-stage section. Tanks, plumbing, the Ship and overall proportions are drawn from the Block 2 model (flew in 2025, retired after Flight 11 on Oct 13 2025).' },
  booster: { ...INFO.booster,
    d: 'Stainless-steel first stage. Burns for ~2.5 minutes, then flips, boosts back and returns to be caught by the launch tower\'s "chopsticks" (or splashes down on test flights). Shown with V3’s 3 grid fins and integrated hot-stage section; internal layout drawn from Block 2.' },
  model: { t: 'Which Starship is this?', tag: 'Model: V3 (approximate)',
    d: 'An approximation of Starship V3 (Block 3). Modelled V3 changes: three grid fins about 50% larger than the four Block 2 fins, mounted lower on the booster (SpaceX says they are also used for lift and catch), and a vented hot-stage section built into the booster instead of a separate, jettisoned ring. Not modelled: V3’s slightly taller stack (~124 m vs ~123 m), larger propellant loads, redesigned fuel transfer tube and Raptor 3 engine details. Those parts use Block 2 geometry, which last flew on Flight 11 (Oct 13 2025).',
    s: [['Model', 'V3 approximation (booster fins + hot stage)'], ['V3 first flight', 'Flight 12 · May 22 2026'], ['Last Block 2 flight', 'Flight 11 · Oct 13 2025'], ['V3 booster', '~72.3 m · ~81 MN (33 × ~250 tf Raptor 3)'], ['V3 propellant', 'Booster ~3,650 t · ship ~1,600 t (reported)'], ['Raptor 3 (SpaceX)', '~250 tf SL · ~275 tf vac']],
    note: 'V3 fin position and vent pattern are approximate; propellant loads come from media/Wikipedia reporting and sources differ.' },
  b_fwd: { t: 'Booster forward section (V3)', tag: 'Super Heavy · structure',
    d: 'Top of the V3 booster above the methane forward dome, now topped by the integrated vented hot-stage section. On V3 the grid fins moved lower, and SpaceX says they double as the lift and catch points.', s: [['Grid fins', '3 (V3) · 4 on Block 1/2']] },
  b_gridfin: { t: 'Grid fins (V3)', tag: 'Super Heavy · aerodynamics',
    d: 'Three steel lattice grid fins, about 50% larger and stronger than the four Block 2 fins, mounted lower on the booster. They steer during boostback and descent and, per SpaceX, are also used to lift and catch the booster. Electrically actuated.',
    s: [['Count', '3 (V3) · 4 (Block 1/2)'], ['Size', '~50% larger than Block 2 (SpaceX)']], note: 'Exact height and pocket shape here are approximate.' },
  hsr: { t: 'Integrated hot-stage section (V3)', tag: 'Interface Ship ↔ booster',
    d: 'Starship "hot stages": the Ship lights its engines while still attached, and the exhaust escapes through vents between the stages. On V3 this vented section is built into the top of the booster and stays attached for recovery instead of being a separate ring that is jettisoned (Block 1/2). SpaceX described "a lot more vent area".',
    s: [['Hot staging first used', 'Flight 2 (Nov 2023)'], ['V3 change', 'Integrated, not jettisoned']], note: 'Vent count and shape drawn here are illustrative.' },
};
